Feat-TelaAlunos
JuannCarloss/front-ged-app pull request #17
Opened 2024-12-09 22:16 UTC by Carrerogabriel

Tela para controle de alunos

## Descrição

[Criação da tela de listagem de alunos, cadastros de alunos, apagar alunos e editar]

## Problema Relacionado

[Se houver uma issue relacionada, mencione-a aqui]

## Checklist

- [X] Eu verifiquei se este pull request está direcionado à branch correta
- [X] Meus commits seguem as [convenções de commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] Eu adicionei/atualizei a documentação necessária (se aplicável)

## Capturas de tela (se aplicável)

[Adicione capturas de tela para ajudar a entender as mudanças, se necessário]

## Notas Adicionais

[Adicione quaisquer notas ou informações adicionais que os revisores precisem saber]

2024-12-09 22:34 UTC, lucas0headshot requested changes
Traduz para português 😃

2024-12-10 14:41 UTC, Carrerogabriel reviewed
Alteração feita conforme solicitado

2024-12-10 22:37 UTC, lucas0headshot commented
Só resolver os conflitos, @Carrerogabriel

2024-12-11 04:47 UTC, lucas0headshot commented
Fecharei para prosseguir com a padronização

2024-12-11 04:47 UTC, closed without merging